CREATE TABLE test_all_datatypes (
    col_bigint          bigint,
    col_int             int,
    col_integer         integer,
    col_smallint        smallint,
    col_tinyint         tinyint,
    col_bit             bit,
    col_decimal         decimal(18, 4),
    col_numeric         numeric(10, 2),
    col_money           money,
    col_smallmoney      smallmoney,
    col_float           float,
    col_real            real,
    col_date            date,
    col_time            time,
    col_datetime        datetime,
    col_datetime2       datetime2(6),
    col_smalldatetime   smalldatetime,
    col_char            char(10),
    col_varchar         varchar(255),
    col_varchar_max     varchar(max),
    col_text            text,
    col_nchar           nchar(10),
    col_nvarchar        nvarchar(255),
    col_nvarchar_max    nvarchar(max),
    col_ntext           ntext,
    col_binary          binary(16),
    col_varbinary       varbinary(255),
    col_varbinary_max   varbinary(max),
    col_image           ime,
    col_uniqueidentifier uniqueidentifier,
    col_xml             xml,
    col_sql_variant     sql_variant,
    col_rowversion      rowversion,
    col_timestamp       timestamp,      